# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/hushicai
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: hushicai

# Baidu share
baidushare: true
